### ISSUE TITLE
Bug in HTTP Handler

### ISSUE THREAD

**Issue by thomascoquet** [airbusgeo/osio#4]
Hello Tom,
I tested a combo of http+zip for osio+godal but never plain HTTP. I guess I misread the following VSIKeyReader comment:
```
// When registering a reader with
//  RegisterVSIHandler("scheme://",handler)
// calling Open("scheme://myfile.txt") will result in godal making calls to
//  VSIReader("myfile.txt")
```
In the HTTP Handler, I assumed the full URL would be returned, instead it is called without the scheme (ie `www.google.com` instead of `https://www.google.com`).

I was wondering how you wanted this to be fixed? 

For example:
```go
httpr, _ := osio.HTTPHandle(ctx)
httpsr, _ := osio.HTTPSHandle(ctx)

httpa, _ := osio.NewAdapter(httpr)
httpsa, _ := osio.NewAdapter(httpsr)

godal.RegisterVSIAdapter("http://", httpa)
godal.RegisterVSIAdapter("https://", httpsa)
```
Thomas

**Comment by thomascoquet** [comment]
Maybe the best would be to always feed the scheme/protocol and let the underlying handler do the `TrimPrefix` if needs be?
I'd argue that the protocol (`http`/ `https`,  `ftp`/`ftps`) is semantically fully part of the "key".

This would not break existing implementation as the scheme is systematically stripped if it exists (https://github.com/airbusgeo/osio/blob/main/uri.go#L19).

**Comment by tbonfort** [comment]
In gdal world, the prefix is only used to register a handler, and is not part of the key (e.g., you use `/vsicurl/https://server/path`), so it is customary for gdal to drop this prefix when forwarding to the underlying handler. In our case we are using the prefix in both ways, thus the mixup we have here.
In theory, in order to not break backwards compatibility we should add a `StripPrefix()` option to `godal.RegisterVSIAdapter` that defaults to `true`. I believe that the use-case is sufficiently widespread that we can tolerate it defaulting to `false`, and make sure that all osio adapters gracefully handle the `prefix://bucket/object` and `bucket/object` keys ( which I believe it the case ). Are you willing to submit a PR to godal for this ?
